version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: staking_postgres
    restart: always
    environment:
      POSTGRES_USER: staking_user
      POSTGRES_PASSWORD: staking_password
      POSTGRES_DB: staking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
